### ISSUE TITLE
[FEATURE-REQUEST] Added a DB model and endpoints for storing details of team members.

### ISSUE THREAD

**Issue by mukul-mehta** [iit-technology-ambit/Syphus#119]
Since we have a contact list, we can add the team members in a DB model. This will make it easier to render on the frontend rather than manually entering details. We can scrape the details from the contact details google sheet and use the Google Drive folder with photos to map photos with a person.

**Comment by thealphadollar** [comment]
This is an overkill, since it'll then involve a lot of automation which is much easier to do manually. We should not do something just because we can do it. Always keep in mind the saving you do and the work that is required upfront.

Please close this issue if you are convinced that it'll be an overkill, otherwise let's have a discussion over this in tomorrow's meeting.
